import { type ContentWarningTag, type MovieGenre, type StyleTag, type WatchContext } from "../constants/taxonomy";
import { type FeatureVector } from "../recommendation/feature-vector";

export type OnboardingMovieSeed = {
  title: string;
  releaseYear: number;
  genrePrimary: MovieGenre;
  genreSecondary?: MovieGenre;
  runtimeMinutes: number;
  features: FeatureVector;
  genres: MovieGenre[];
  watchContexts: WatchContext[];
  contentWarnings: ContentWarningTag[];
  styleTags: StyleTag[];
};

export const ONBOARDING_MOVIES_V1: OnboardingMovieSeed[] = [
  {
    title: "La La Land",
    releaseYear: 2016,
    genrePrimary: "musical",
    genreSecondary: "romance",
    runtimeMinutes: 128,
    features: { moodCalm: 0.46, moodDark: 0.26, moodEmotional: 0.78, moodUplifting: 0.74, toneStylish: 0.84, toneFunny: 0.34, paceFast: 0.55, paceSlowBurn: 0.45, complexity: 0.44, emotionalWeight: 0.68, tension: 0.34, accessibility: 0.79 },
    genres: ["musical", "romance", "drama"],
    watchContexts: ["date_friendly", "friends_hangout"],
    contentWarnings: ["sad_ending"],
    styleTags: ["easy_to_watch"],
  },
  {
    title: "Her",
    releaseYear: 2013,
    genrePrimary: "romance",
    genreSecondary: "sci-fi",
    runtimeMinutes: 126,
    features: { moodCalm: 0.74, moodDark: 0.42, moodEmotional: 0.84, moodUplifting: 0.38, toneStylish: 0.76, toneFunny: 0.24, paceFast: 0.28, paceSlowBurn: 0.72, complexity: 0.58, emotionalWeight: 0.81, tension: 0.32, accessibility: 0.57 },
    genres: ["romance", "sci-fi", "drama"],
    watchContexts: ["solo_watch", "late_night_fit", "date_friendly"],
    contentWarnings: ["sad_ending"],
    styleTags: ["slow_burn"],
  },
  {
    title: "Interstellar",
    releaseYear: 2014,
    genrePrimary: "sci-fi",
    genreSecondary: "drama",
    runtimeMinutes: 169,
    features: { moodCalm: 0.42, moodDark: 0.45, moodEmotional: 0.8, moodUplifting: 0.52, toneStylish: 0.71, toneFunny: 0.08, paceFast: 0.49, paceSlowBurn: 0.51, complexity: 0.82, emotionalWeight: 0.85, tension: 0.61, accessibility: 0.49 },
    genres: ["sci-fi", "drama", "adventure"],
    watchContexts: ["solo_watch", "friends_hangout"],
    contentWarnings: [],
    styleTags: ["complex_plot"],
  },
  {
    title: "Blade Runner 2049",
    releaseYear: 2017,
    genrePrimary: "sci-fi",
    genreSecondary: "drama",
    runtimeMinutes: 164,
    features: { moodCalm: 0.24, moodDark: 0.86, moodEmotional: 0.52, moodUplifting: 0.14, toneStylish: 0.93, toneFunny: 0.03, paceFast: 0.22, paceSlowBurn: 0.78, complexity: 0.74, emotionalWeight: 0.65, tension: 0.57, accessibility: 0.31 },
    genres: ["sci-fi", "drama", "thriller"],
    watchContexts: ["solo_watch", "late_night_fit"],
    contentWarnings: ["violence"],
    styleTags: ["slow_burn", "visual_masterpiece"],
  },
  {
    title: "The Grand Budapest Hotel",
    releaseYear: 2014,
    genrePrimary: "comedy",
    genreSecondary: "adventure",
    runtimeMinutes: 99,
    features: { moodCalm: 0.55, moodDark: 0.22, moodEmotional: 0.39, moodUplifting: 0.7, toneStylish: 0.94, toneFunny: 0.76, paceFast: 0.59, paceSlowBurn: 0.41, complexity: 0.53, emotionalWeight: 0.38, tension: 0.31, accessibility: 0.86 },
    genres: ["comedy", "adventure"],
    watchContexts: ["friends_hangout", "date_friendly"],
    contentWarnings: [],
    styleTags: ["easy_to_watch", "visual_masterpiece"],
  },
  {
    title: "Whiplash",
    releaseYear: 2014,
    genrePrimary: "drama",
    genreSecondary: "musical",
    runtimeMinutes: 106,
    features: { moodCalm: 0.12, moodDark: 0.54, moodEmotional: 0.73, moodUplifting: 0.27, toneStylish: 0.66, toneFunny: 0.06, paceFast: 0.82, paceSlowBurn: 0.18, complexity: 0.62, emotionalWeight: 0.74, tension: 0.92, accessibility: 0.55 },
    genres: ["drama", "musical"],
    watchContexts: ["solo_watch", "late_night_fit"],
    contentWarnings: ["disturbing"],
    styleTags: ["easy_to_watch"],
  },
  {
    title: "Before Sunrise",
    releaseYear: 1995,
    genrePrimary: "romance",
    genreSecondary: "drama",
    runtimeMinutes: 101,
    features: { moodCalm: 0.86, moodDark: 0.16, moodEmotional: 0.74, moodUplifting: 0.61, toneStylish: 0.63, toneFunny: 0.28, paceFast: 0.18, paceSlowBurn: 0.82, complexity: 0.43, emotionalWeight: 0.67, tension: 0.17, accessibility: 0.88 },
    genres: ["romance", "drama"],
    watchContexts: ["date_friendly", "solo_watch"],
    contentWarnings: [],
    styleTags: ["slow_burn", "easy_to_watch"],
  },
  {
    title: "Spider-Man: Into the Spider-Verse",
    releaseYear: 2018,
    genrePrimary: "animation",
    genreSecondary: "action",
    runtimeMinutes: 117,
    features: { moodCalm: 0.36, moodDark: 0.21, moodEmotional: 0.61, moodUplifting: 0.89, toneStylish: 0.96, toneFunny: 0.68, paceFast: 0.91, paceSlowBurn: 0.09, complexity: 0.52, emotionalWeight: 0.57, tension: 0.63, accessibility: 0.92 },
    genres: ["animation", "action", "adventure"],
    watchContexts: ["friends_hangout", "family_time"],
    contentWarnings: ["violence"],
    styleTags: ["easy_to_watch", "visual_masterpiece"],
  },
  {
    title: "Zodiac",
    releaseYear: 2007,
    genrePrimary: "thriller",
    genreSecondary: "crime",
    runtimeMinutes: 157,
    features: { moodCalm: 0.11, moodDark: 0.87, moodEmotional: 0.34, moodUplifting: 0.09, toneStylish: 0.64, toneFunny: 0.04, paceFast: 0.36, paceSlowBurn: 0.64, complexity: 0.84, emotionalWeight: 0.62, tension: 0.88, accessibility: 0.31 },
    genres: ["thriller", "crime", "mystery"],
    watchContexts: ["solo_watch", "late_night_fit"],
    contentWarnings: ["violence", "disturbing"],
    styleTags: ["slow_burn", "complex_plot"],
  },
  {
    title: "Paddington 2",
    releaseYear: 2017,
    genrePrimary: "family",
    genreSecondary: "comedy",
    runtimeMinutes: 103,
    features: { moodCalm: 0.71, moodDark: 0.07, moodEmotional: 0.55, moodUplifting: 0.95, toneStylish: 0.67, toneFunny: 0.82, paceFast: 0.58, paceSlowBurn: 0.42, complexity: 0.24, emotionalWeight: 0.43, tension: 0.2, accessibility: 0.98 },
    genres: ["family", "comedy"],
    watchContexts: ["family_time", "friends_hangout"],
    contentWarnings: [],
    styleTags: ["easy_to_watch"],
  },
  {
    title: "Parasite",
    releaseYear: 2019,
    genrePrimary: "thriller",
    genreSecondary: "drama",
    runtimeMinutes: 132,
    features: { moodCalm: 0.19, moodDark: 0.79, moodEmotional: 0.59, moodUplifting: 0.18, toneStylish: 0.78, toneFunny: 0.33, paceFast: 0.67, paceSlowBurn: 0.33, complexity: 0.83, emotionalWeight: 0.72, tension: 0.82, accessibility: 0.58 },
    genres: ["thriller", "drama", "comedy"],
    watchContexts: ["friends_hangout", "solo_watch"],
    contentWarnings: ["violence", "disturbing"],
    styleTags: ["complex_plot"],
  },
  {
    title: "Inside Out",
    releaseYear: 2015,
    genrePrimary: "animation",
    genreSecondary: "family",
    runtimeMinutes: 95,
    features: { moodCalm: 0.62, moodDark: 0.18, moodEmotional: 0.89, moodUplifting: 0.83, toneStylish: 0.58, toneFunny: 0.72, paceFast: 0.57, paceSlowBurn: 0.43, complexity: 0.37, emotionalWeight: 0.76, tension: 0.29, accessibility: 0.97 },
    genres: ["animation", "family", "comedy"],
    watchContexts: ["family_time", "solo_watch", "friends_hangout"],
    contentWarnings: [],
    styleTags: ["easy_to_watch"],
  },
  {
    title: "Gone Girl",
    releaseYear: 2014,
    genrePrimary: "thriller",
    genreSecondary: "mystery",
    runtimeMinutes: 149,
    features: { moodCalm: 0.14, moodDark: 0.88, moodEmotional: 0.47, moodUplifting: 0.08, toneStylish: 0.74, toneFunny: 0.06, paceFast: 0.52, paceSlowBurn: 0.48, complexity: 0.71, emotionalWeight: 0.66, tension: 0.86, accessibility: 0.36 },
    genres: ["thriller", "mystery", "drama"],
    watchContexts: ["solo_watch", "late_night_fit"],
    contentWarnings: ["violence", "disturbing"],
    styleTags: ["complex_plot"],
  },
  {
    title: "Little Miss Sunshine",
    releaseYear: 2006,
    genrePrimary: "comedy",
    genreSecondary: "drama",
    runtimeMinutes: 101,
    features: { moodCalm: 0.57, moodDark: 0.24, moodEmotional: 0.69, moodUplifting: 0.79, toneStylish: 0.49, toneFunny: 0.71, paceFast: 0.43, paceSlowBurn: 0.57, complexity: 0.36, emotionalWeight: 0.64, tension: 0.33, accessibility: 0.9 },
    genres: ["comedy", "drama"],
    watchContexts: ["family_time", "friends_hangout"],
    contentWarnings: [],
    styleTags: ["easy_to_watch"],
  },
];

export const ONBOARDING_MOVIE_TITLE_SET = new Set(ONBOARDING_MOVIES_V1.map((movie) => movie.title));
